(function (window) {
  "use strict";

  window.DairyFedKnowledge = {
    overview: "DairyFed is designed as the digital infrastructure for India's cooperative dairy ecosystem: one information layer connecting farmers, village societies, district unions, state federations, government departments, veterinary services, banks and insurance. Its core idea is one platform, every stakeholder, one connected ecosystem.",
    problem: "India's dairy network is physically connected, but information can remain fragmented across registers, phone calls, circulars and memory. DairyFed addresses slow feedback loops, limited visibility into milk quality and payments, manual reporting, fragmented communication, limited scheme awareness and difficult access to veterinary services.",
    farmers: "DairyFed is designed to give farmers milk collection history, milk quality reports, payment status, digital records, government scheme information, advisories, complaint tracking, veterinary-service access and notifications. This chatbot cannot access an individual farmer's live records.",
    cooperative: "A cooperative dashboard is designed for farmer database management, milk procurement, daily collection, digital circulars, automated report generation and complaint-resolution tracking. It aims to reduce paperwork and improve member engagement.",
    federation: "A federation dashboard is designed for district-level analytics, society performance benchmarking, milk procurement trend analysis, a unified communication hub and AI-assisted decision support.",
    structure: "The three cooperative tiers are the village society, district union and state federation. They have different responsibilities, while DairyFed aims to improve information flow across the layers.",
    collection: "The Milk Collection and Quality Records engine is designed to keep digital procurement history, collection history, FAT and SNF records, and farmer-wise digital records.",
    quality: "FAT is the fat content measured in milk, while SNF means solids-not-fat, the milk solids other than fat. DairyFed's platform is designed to record FAT and SNF alongside milk collection and quality history. It does not provide this chatbot with a farmer's actual test result or rate.",
    payments: "The Payments and Financial Transparency engine is designed to provide payment tracking, digital payment history, settlement notifications and financial records. The platform is designed to provide real-time payment status, but this chatbot cannot access an individual's bank or payment account.",
    communication: "The Communication and Notifications engine is designed for circulars, collection alerts, emergency announcements and personalized notifications, reducing fragmented information channels across the cooperative ecosystem.",
    schemes: "The Government Schemes and Services module is designed to provide scheme eligibility information, application guidance, training programmes and extension services. I do not have verified DairyFed information about a specific scheme name, amount, deadline or link.",
    veterinary: "The Veterinary and Animal Health module is designed for vaccination reminders, artificial insemination requests, veterinary booking and disease alerts. It can explain platform features, but it cannot diagnose an animal or prescribe treatment. For urgent animal-health concerns, contact a qualified veterinarian.",
    complaints: "DairyFed is designed to digitize complaint and grievance tracking, helping cooperatives see progress toward resolution. This chatbot cannot file, inspect or confirm a specific complaint.",
    analytics: "Analytics and Governance is designed to support procurement analytics, society performance views, district dashboards and decision support. The materials describe AI-assisted decision support and AI-powered analytics, without specifying a particular model or accuracy.",
    records: "DairyFed is designed to centralize digital records, create digital audit trails and improve operational visibility. I do not have enough verified information to make a specific security or certification claim.",
    roadmap: "DairyFed's proposed roadmap has four stages: Phase 1 pilot with selected cooperatives, digitized collection records and a farmer portal; Phase 2 district expansion with multiple cooperatives, a federation dashboard and digital communication; Phase 3 statewide integration with federations, government services and veterinary networks; Phase 4 national scale with multi-state expansion, AI-powered analytics and financial-services integration. These are roadmap stages, not a claim that every phase is complete.",
    market: "According to DairyFed's pitch materials, India's dairy sector produces over 230 million tonnes annually, with 190K+ cooperative societies and 80M+ dairy farming households dependent on cooperative networks. These are figures cited in the pitch materials, not independently verified live statistics.",
    business: "DairyFed's pitch materials describe a business model around platform and ecosystem services, including marketplace and digital-payment opportunities. Any revenue figures or user numbers in the deck are projections, not achieved results.",
    funding: "DairyFed's pitch materials describe a $1 million capital allocation across Technology Platform and AI, Farmer and Federation Acquisition, Marketplace and Digital Payments, Sales and Strategic Partnerships, Marketing and Brand Building, Product Innovation, Legal and Compliance, and Working Capital. This does not mean the amount has already been raised.",
    projections: "The pitch deck contains illustrative five-year projections for milk federations, marketplace sellers, premium members, marketplace users, financial-service users, AI analytics clients, government and enterprise partners, and projected revenue. These are illustrative projections from the pitch deck, not current results.",
    contact: "You can contact DairyFed at globalexpressgroup@gmail.com, +91 96505 60277 or +91 99101 96123. Address: 13, Institutional Area, Lodhi Road, New Delhi 110003.",
    fallback: "I can help you explore DairyFed's digital dairy ecosystem, farmer services, cooperative tools, federation dashboards, payments, milk quality, government schemes, veterinary support, analytics and more. What would you like to know?",
    unrelated: "I'm focused on DairyFed and its cooperative dairy ecosystem, so I may not have reliable information about that topic. Try asking about farmers, milk collection, payments, veterinary services, cooperatives, federations or DairyFed's platform.",
    safety: "I can explain DairyFed's veterinary-service features, but I can't diagnose an animal or prescribe treatment. Please contact a qualified veterinarian for medical advice."
  };
})(window);
